FROM us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.2-2.py310:latest

WORKDIR /root

RUN pip install einops
RUN pip install pycocotools

# Copy your training code
COPY datasets /root/datasets
COPY models /root/models
COPY util /root/util
COPY main.py /root/main.py
COPY engine.py /root/engine.py

# Set the entrypoint for your training script
ENTRYPOINT ["python", "main.py"]